
services:
  - type: web
    name: nowledge-base-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node server/server.js"
    plan: free
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
